### ISSUE TITLE
Error when using --headful 

### ISSUE THREAD

**Issue by AbdullahTrees** [Makepad-fr/fbjs#75]
I want to download all the memes in [this group]( https://www.facebook.com/sadnibbahourshitposting/photos)
```
C:\Users\Abdullah>fgps --group-ids sadnibbahourshitposting --output "C:\Users\Abdullah\Desktop\fb test" --headful
Cookie banner did not appear
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

Error: No node found for selector: input#email
    at assert (C:\Users\Abdullah\AppData\Roaming\npm\node_modules\facebook-group-posts-scraper\node_modules\puppeteer\lib\helper.js:283:11)
    at DOMWorld.focus (C:\Users\Abdullah\AppData\Roaming\npm\node_modules\facebook-group-posts-scraper\node_modules\puppeteer\lib\DOMWorld.js:376:5)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async facebookLogIn (C:\Users\Abdullah\AppData\Roaming\npm\node_modules\facebook-group-posts-scraper\src\index.js:349:3)
    at async main (C:\Users\Abdullah\AppData\Roaming\npm\node_modules\facebook-group-posts-scraper\src\index.js:612:10)
  -- ASYNC --
    at Frame.<anonymous> (C:\Users\Abdullah\AppData\Roaming\npm\node_modules\facebook-group-posts-scraper\node_modules\puppeteer\lib\helper.js:111:15)
    at Page.focus (C:\Users\Abdullah\AppData\Roaming\npm\node_modules\facebook-group-posts-scraper\node_modules\puppeteer\lib\Page.js:1071:29)
    at facebookLogIn (C:\Users\Abdullah\AppData\Roaming\npm\node_modules\facebook-group-posts-scraper\src\index.js:349:14)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async main (C:\Users\Abdullah\AppData\Roaming\npm\node_modules\facebook-group-posts-scraper\src\index.js:612:10)

Node.js v17.2.0
```

I'm using headful mode because if I don't put the `--headful` flag, I don't see anything on my output folder, so the program is essentially doing nothing.

**Comment by AbdullahTrees** [comment]
May as well add what happens if I try doing it without `--headful`, ...

```
C:\Users\Abdullah>fgps --group-ids sadnibbahourshitposting --output "C:\Users\Abdullah\Desktop\fb test"
Cookie banner did not appear
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

TimeoutError: waiting for XPath "//article/div[@class="story_body_container"]" failed: timeout 30000ms exceeded
    at new WaitTask (C:\Users\Abdullah\AppData\Roaming\npm\node_modules\facebook-group-posts-scraper\node_modules\puppeteer\lib\DOMWorld.js:549:28)
    at DOMWorld._waitForSelectorOrXPath (C:\Users\Abdullah\AppData\Roaming\npm\node_modules\facebook-group-posts-scraper\node_modules\puppeteer\lib\DOMWorld.js:478:22)
    at DOMWorld.waitForXPath (C:\Users\Abdullah\AppData\Roaming\npm\node_modules\facebook-group-posts-scraper\node_modules\puppeteer\lib\DOMWorld.js:441:17)
    at Frame.waitForXPath (C:\Users\Abdullah\AppData\Roaming\npm\node_modules\facebook-group-posts-scraper\node_modules\puppeteer\lib\FrameManager.js:642:47)
    at Frame.<anonymous> (C:\Users\Abdullah\AppData\Roaming\npm\node_modules\facebook-group-posts-scraper\node_modules\puppeteer\lib\helper.js:112:23)
    at Page.waitForXPath (C:\Users\Abdullah\AppData\Roaming\npm\node_modules\facebook-group-posts-scraper\node_modules\puppeteer\lib\Page.js:1131:29)
    at facebookMain (C:\Users\Abdullah\AppData\Roaming\npm\node_modules\facebook-group-posts-scraper\src\index.js:471:16)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async main (C:\Users\Abdullah\AppData\Roaming\npm\node_modules\facebook-group-posts-scraper\src\index.js:617:5)

Node.js v17.2.0
```
